[build]
  command = "echo 'No build'"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[functions]
  external_node_modules = ["yt-dlp-wrap"]
  node_bundler = "esbuild"
